imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

#http login for test env
security:
    encoders:
        Kpb\UserBundle\Entity\User: plaintext
    firewalls:
        main:
            http_basic:
                provider: test_provider