parameters:
#    kpb_quote.example.class: Kpb\QuoteBundle\Example

services:
#    kpb_quote.example:
#        class: %kpb_quote.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
